export default {
	API_LOADING_START: 'API_LOADING_START',
	API_LOADING_END: 'API_LOADING_END',
	SET_DEVICE_HEIGHT: 'SET_DEVICE_HEIGHT',

	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',

	SET_NEW_NOTE: 'SET_NEW_NOTE',
	LOADING_NEW_NOTE: 'LOADING_NEW_NOTE',
	SET_UPDATE_NOTE: 'SET_UPDATE_NOTE',
	REMOVE_ITEM_NOTE: 'REMOVE_ITEM_NOTE',
	FILTER_TODOS: 'FILTER_TODOS',
};
